### ISSUE TITLE
Move development environment from hgwdev to cloud

### ISSUE THREAD

**Issue by claymfischer** [HumanCellAtlas/hca-tuatara#18]
A more identical system for testing would be beneficial. Create a new amazon instance, assign a subdomain (perhaps test.tuatara.data.humancellatlas.org) and begin using it as test eviroment instead of hgwdev.

**Comment by galt** [comment]
ec2 machine for production is basically ready now.
We could do a final update and then turn it on for use any time now.

**Comment by galt** [comment]
I am not sure we need to have development in the cloud.
Maybe staging in the clould would be good.

**Comment by claymfischer** [comment]
The environments have been created.
