### ISSUE TITLE
Concept of a cohort or group label

### ISSUE THREAD

**Issue by claymfischer** [HumanCellAtlas/hca-tuatara#2]
In chatting with @jahilton I became curious if we should consider applying a label for grouping data sets. This would give an interesting perspective for tracking datasets and seeing shared pain points.

For instance, we could label three datasets as the _preview_, some as the 16 available during the _soft launch_ or _CBeta_, and some as _Barcelona incentives_.

@pnejad @cjvillar @willrockout any objections?

**Comment by cjvillar** [comment]
Sounds useful.

**Comment by pnejad** [comment]
@claymfischer This sounds like a helpful label to add! But where would this be added? To Github tickets, tuatara or the metadata?

**Comment by claymfischer** [comment]
I think this would be best in Tuatara @pnejad.

**Comment by JimKent** [comment]
This is implemented on the development branch now. Theres a new 'x tag'  table that I populated with 'preview', 'soft launch' and 'Barcelona incentives.'  There's a tags field in the project table that appears in the overall section now.'

**Comment by claymfischer** [comment]
Excellent! Thank you, Jim.
