### ISSUE TITLE
New user accounts and reset password?

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/hca-tuatara#23]
We set up user accounts at the recent broad F2F but I can no longer login with the credentials I thought we had set up. username was `marion`. Not sure if user accounts were lost when moving to the new web address or I recorded my password wrong. It may be good to implement some kind of basic 'forgot password' functionality though. In the meantime if my password could be reset or account regenerated that would be grand.

We also have two new starters, @javfg and @rays22, so it would be great if they could also be set up with accounts

**Comment by mshadbolt** [comment]
further clarification: I can login to the previous website http://hgwdev.gi.ucsc.edu:8124/admin/ but not the new one https://tuatara.data.humancellatlas.org/admin/login/?next=/admin/

Not sure if the new one is an exact replica or if updates will only show at the new address from here on in?

**Comment by lauraclarke** [comment]
Can I get a user account too?

**Comment by ESapenaVentura** [comment]
+1 please

**Comment by zperova** [comment]
I can not access with the credentials I have been given at the F2F. My usename is 'zina'

**Comment by claymfischer** [comment]
I have our engineer looking into this, but I am happy to setup a time at 4pm BST / 8 AM PST to reset these. Does tomorrow (Friday) at 8am work for anyone?

**Comment by galt** [comment]
port 8124 is Jim Kent's testing instance.
Why were credentials for the user created there?
I certainly have NOT been syncing anything in the db between jim's test instance and the new production instance. That was never in the plan. 
(FYI port 8123 was the old production instance, now defunct and we will not re-use that port number)

**Comment by galt** [comment]
It looks like these users were incorrectly registered under jim's 8124 test instance
and not on the old production 8123.

Thus they do not appear in hcat db but rather jim's testing db:

MariaDB [hcat]> select id, first_name, last_name, email, is_staff, is_active from kentDjangoTest5.auth_user;
+----+-------------+----------------+--------------------------+----------+-----------+
| id | first_name  | last_name      | email                    | is_staff | is_active |
+----+-------------+----------------+--------------------------+----------+-----------+
[... existing stuff not shown]
| 13 | Zina        | Perova         | zina@ebi.ac.uk           |        1 |         1 |
| 14 | Marion      |                | mshadbolt@ebi.ac.uk      |        1 |         1 |
| 15 | Enrique     | Sapena Ventura | enrique@ebi.ac.uk        |        1 |         1 |
| 16 | Oihane      |                | ofano@ebi.ac.uk          |        1 |         1 |
| 17 | Jenny       | Chien          | jychien@stanford.edu     |        1 |         1 |
| 18 | Jennifer    | Zamanian       | jlz@stanford.edu         |        1 |         1 |
| 19 |             |                |                          |        1 |         1 |
+----+-------------+----------------+--------------------------+----------+-----------+

**Comment by claymfischer** [comment]
We set up a handful of EBI users to test Tuatara and give user feedback suggestions during a breakout session at our recent DCP meeting. It was understood that we were interacting with a development environment and things could be wiped out at any time, with a production instance going live at tuatara.data.humancellatlas.org later on. I'll setup video conferences to get everyone established on the production instance.

**Comment by mshadbolt** [comment]
@claymfischer I am not available today at 4pm, next Tues/Wed at the same time would work for me.

**Comment by lauraclarke** [comment]
@claymfischer if the accounts could be setup and passwords emailed to us for everyone who already had an account and then myself, Ray and Javier that would be great

I am aware that we all have limited time between now and Christmas so if people can get the accounts before then it would be great

thanks

**Comment by claymfischer** [comment]
@mshadbolt let's meet Tuesday at 4pm BST and I can tell you the password there, and you can distribute to the group.

**Comment by mshadbolt** [comment]
@claymfischer sounds good, speak to you tomorrow

**Comment by zperova** [comment]
thanks @mshadbolt and @claymfischer

**Comment by ESapenaVentura** [comment]
Thanks!

**Comment by claymfischer** [comment]
Wonderful chat with @mshadbolt, set up passwords for the users gabs, laura, zina, enrique, javier, ray. Usernames are lowercase. Marion has the password.

We will be extending accounts to the rest of the group once we get some real data into it (Jason's team, Ambrose, Parth, etc).

**Comment by mshadbolt** [comment]
Thanks @claymfischer 

I will reopen the issue if we encounter any problems.
