### ISSUE TITLE
Security certificate issue

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/hca-tuatara#24]
When I try to access https://tuatara.data.humancellatlas.org/ my browser tells me it is unsafe to proceed due to an issue with the security certificate.

![Screenshot 2020-01-06 at 16 55 43](https://user-images.githubusercontent.com/13007987/71833673-5ca0ca80-30a5-11ea-9a07-6c1a4a016ef2.png)

**Comment by galt** [comment]
It looks like it has expired.
Expired: Thursday, December 26, 2019 at 6:19:15 AM Pacific Standard Time
I asked Parth Shah to renew it.

**Comment by claymfischer** [comment]
Thanks @mshadbolt and @galt!

**Comment by galt** [comment]
I figured out that we installed that certificate ourselves and I renewed it.
The default cert will expire every 6 months.
Currently the renewal process is pretty simple, and I have documented it better in our
internal makedoc on our server.  This should now work without complaining
about the expired cert.

https://tuatara.data.humancellatlas.org/
