### ISSUE TITLE
COVID-19 dashboard: shortName and popover 

### ISSUE THREAD

**Issue by claymfischer** [HumanCellAtlas/hca-tuatara#27]
1) The shortname should be truncated (not sure how many characters, perhaps 75?)
2) When hoving over the shortName, the title and description should be displayed. 

We don't want to overload the popover. Maybe in the future we could have 'date created' and 'date last modified', but additional stuff is considered out of scope for now.

**Comment by willrockout** [comment]
@claymfischer I've implemented the popover but a lot of the descriptions are super lengthy. How long should they before I truncate them? I can truncate by words or character counts.

**Comment by willrockout** [comment]
Added to COVID-19 dashboard with descriptions truncated to 100 words.
