### ISSUE TITLE
COVID-19 dashboard: for array data, break line

### ISSUE THREAD

**Issue by claymfischer** [HumanCellAtlas/hca-tuatara#28]
Array data is often separated with a comma. This doesn't always make sense, for example consider:
`fischer,clay` and `sullivan,william` being printed as `fischer,clay,sullivan,william`. For now we can use `<br />` to separate array data. 

There is a chance that some arrays will contain a many values. For now we'll assume it's rare enough to not be a concern.

**Comment by willrockout** [comment]
@claymfischer This has been implemented for the covid19 lab's field. I have built-in logic so that labs are truncated to just 2 and you won't see a popover unless there are more than 2 labs.

**Comment by claymfischer** [comment]
Thank you!
