### ISSUE TITLE
Update to submission section on project info page

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/hca-tuatara#4]
We propose the following changes to the submission section on the project info page.

**Page**: Project info 
Capitalize header
Change "TAndC" to "T&C"
Move shared google sheet above "sheet template date"
Lab review date move above submit date
Remove staging area date
We only care about the final sheet thats submitted ( remove sheet validated row)
Add “sheet submitted”

**Comment by JimKent** [comment]
I think I addressed all this in the next version  now on the dev site.

**Comment by JimKent** [comment]
Also now on internal production site.
