### ISSUE TITLE
index.html page

### ISSUE THREAD

**Issue by claymfischer** [HumanCellAtlas/hca-tuatara#7]
Creating an issue for what folks might want on the index.html page. 

So far I am focused on explaining what Tuatara is, how to get access, and a guide to the API.

**Comment by maximilianh** [comment]
Done. Also activated the http -> https redirect.

**Comment by maximilianh** [comment]
(for some reason, I can't close this ticket)

**Comment by JimKent** [comment]
Maybe just as well ticket is still open.  I fleshed out the API parts and edited down the rest, and got a Tuatara image.  It and v0.9 of the software, database and media directory still need to get to tuatara.data.humancellatlas.org's EC2 instance.

**Comment by maximilianh** [comment]
From where on hgwdev? Is this only code? If yes, it could come out of the git repo. Should the database also be moved from hgwdev?

How about the future: will future updates be about the code or also include the database?

**Comment by claymfischer** [comment]
@willrockout is now fleshing out some dashboards, and there is a chance our splash page will be partitioned out to individual API and help pages. Closing this for now, and will create a new ticket when the time comes.
